# Generated by Django 5.0.7 on 2024-07-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category_filter',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('housekeeping', 'Housekeeping'), ('food', 'Food'), ('electronics', 'Electronics'), ('services', 'Services'), ('tourism', 'Tourism')], default='None', max_length=40),
        ),
    ]
